### PR TITLE
 #167319073 configured Dotenv variables 

### PR DESCRIPTION
**Pull request by nshutijonathan**
### What does this PR do?
- Install and setup dotenv for the API to manage environment variables
### Description of Task to be completed?
- installed dotenv package
- configured environment variables 
### How should this be manually tested?
- Clone the repo, run npm install , create .env file in the root folder then  save from there your variables
### any background context you want to provide?
-I branched out from the master, then deleted some configurations in order to go-ahead with sequelize 
### What are the relevant pivotal tracker stories?
- [#167319073](https://www.pivotaltracker.com/n/projects/2372121/stories/167319073)

### CODE REVIEW

**Review by habinezadalvan — COMMENTED** [review]
On my behalf, I think that's it; because the dotenv package is installed and .env file is in the .gitignore file.

**Review by nkalyesubula — COMMENTED** [review]
In your documentation on how to use the dotenv, you missed adding a secret key variable for securing the JWT  tokens. And also Regarding the custom port you added, I think it's not necessary. The default one is okay but the custom one should be automatically generated in case the default one is taken.

**Review by minega25 — CHANGES_REQUESTED** [review]
For Github and pivotal tracker integration the below are the only allowed Keywords used in commits.
[(Finishes|Fixes|Delivers) #TRACKER_STORY_ID]

**Comment by Mnickii** [comment]
A few reviews left by your team mates.

**Review by salviosage — COMMENTED** [review]
great work. however, it will be great if on a PR description including what  should be included in dotenv files and the variables names

**Comment by nshutijonathan** [comment]
> For Github and pivotal tracker integration the below are the only allowed Keywords used in commits.
> [(Finishes|Fixes|Delivers) #TRACKER_STORY_ID]
I have changed the commits

**Review by Anguandia — APPROVED** [review]

**Review by habinezadalvan — APPROVED** [review]
I think you are good to go.

**Review by minega25 — APPROVED** [review]

**Pull request merged**
