### PR TITLE
#167313411 Authenticated users should be able to tag articles

### PR DESCRIPTION
**Pull request by Anguandia**
#### What does this PR do?

  Add article tagging feature

#### Description of Task to be completed?

  - Orphan tag creation
  - Orphan tag name change
  - Simultaneous multi-tagging of a given article
  - Single individual tagging of a given article
  - Getting all articles with a given tag
  - Getting all tags of a given article
  - Getting a specific tag
  - Updating and deleting article tags
  - Duplicate tagging prevention
  - Tag limit enforcement to 5
  - Tag length limit enforcement to 3 words

#### How should this be manually tested?

  - Tag creation:
    post/baseUrl/api/v1/tags request with a body {name: Your tag name}
  - Tagging an article:
    post/baseUrl/articles/:articleId/:your-tag-name
  - Updating a tag:
    patch/base-url/tags/:old tag name with a body {update: new tag name}
  - Updating a specific tag of an article:
    patch/articles/:articleId/:tagName with a body {name: tagName}
  - Getting all articles with a given tag:
    get/tags/:tagName/articles
  - Getting all tags of a given article:
    get/articles/:articleId/tags
  - Getting all tags:
    get/tags
  - Deleting a tag:
    delete/tags/:tagName
  - Deleting a specific tag of a specific article
    delete/articles/:articleId/:tagName

#### What are the relevant pivotal tracker stories?

  [#167313411](https://www.pivotaltracker.com/story/show/167313411)
#### Screenshots (if appropriate)

tag an article 

Screen Shot 2019-08-27 at 09 33 52

get article's tags

Screen Shot 2019-08-27 at 09 39 03

update an article's tag

Screen Shot 2019-08-27 at 09 43 52

delete all articles with a given tag

Screen Shot 2019-08-27 at 09 46 58

### CODE REVIEW

**Comment by Mnickii** [comment]
@Anguandia screenshots?

**Review by minega25 — APPROVED** [review]
LGTM

**Review by habinezadalvan — DISMISSED** [review]

**Review by habinezadalvan — COMMENTED** [review]
@minega25 please fix the travis issue.

**Review by nshutijonathan — COMMENTED** [review]
Would You please add some screenshots in postman

**Review by nkalyesubula — APPROVED** [review]
LGTM

**Review by Mnickii — APPROVED** [review]
LGTM

**Pull request merged**
