### PR TITLE
#167313396 Build out Admin REST endpoints for resources(CRUD)

### PR DESCRIPTION
**Pull request by nshutijonathan**
#### What does this PR do?
- Have super admin created automatically
- Have admin endpoints built out 
- Have the admin's endpoints tested
#### Description of Task to be completed?
- Implemented TDD practice
- Protected Admin Routes
- Implemented role based Authorizations
- CRUD operations on admin 
 Have The following endpoint working and tested
*   POST/localhost/api/v1/users/login
*   POST/localhost/api/v1/users/signup
*   GET/localhost/api/v1/users/allusers
*   GET/localhost /api/v1/users/1
*   DELETE/localhost/api/v1/users/5
*   POST/localhost/api/v1/users/signup/admin
* PUT/ocalhost/api/v1/users/update/xxx@gmail.com
#### How should this be manually tested?
* Download or clone the tutorial project code from [this repo](https://github.com/andela/codepirates-ah-backend.git),Install all required NPM  packages by running NPM install from the command line in the project root folder (where the package.json is located).
* Start the API by running NPM  start from the command line in the project root folder, you should see the message Server listening on port 8000. You can test the API directly using an application such as Postman or you can test it with one of the single pages in the browser.
* to test authentication and authorization, add this to the header 
Key: :x-access-token,value:JWT TOKEN
#### What are the relevant pivotal tracker stories?
[#167313421](https://www.pivotaltracker.com/n/projects/2372121/stories/167313421)

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Review by habinezadalvan — COMMENTED** [review]
@nshutijonathan This is great work done. However, travis-ci tests are failing. We need to find out why.

**Comment by Anguandia** [comment]
Good work Jonathan. Tests run error says data and salt required. I think it for hashing the password, a salt is needed which is randomly generated, but property should also be defined in user model. Am not exactly sure but maybe we need to look that up

**Review by nkalyesubula — CHANGES_REQUESTED** [review]
Good work Jonathan. Tests are failing though because there is a variable for you're calling in seeders migration when creating super admin password but travis can't get access to it. We need to create that create in travis CI environment.  Further more please create a .env.sample so that we may know all the expected variables to work with.

**Comment by nshutijonathan** [comment]
> Good work Jonathan. Tests are failing though because there is a variable for you're calling in seeders migration when creating super admin password but travis can't get access to it. We need to create that create in travis CI environment. Further more please create a .env.sample so that we may know all the expected variables to work with.

Thank you! Please I have pushed .env.sample

**Comment by nshutijonathan** [comment]
> @nshutijonathan This is great work done. However, travis-ci tests are failing. We need to find out why.

We are sorting out this

**Review by Mnickii — APPROVED** [review]
LGTM

**Review by minega25 — APPROVED** [review]

**Review by nkalyesubula — APPROVED** [review]

**Review by Anguandia — APPROVED** [review]
Great work Jonathan and all

**Pull request merged**
