### PR TITLE
#167313404 Users should be able to give a rating to an article

### PR DESCRIPTION
**Pull request by minega25**
#### What does this PR do?
Users should be able to give a rating to an article
#### How should this be manually tested?
- `git checkout -b ft-user-rate-article-167313404`
- `git pull origin ft-user-rate-article-167313404`
- `npm run dev`
- Using postman test using the following endpoints

1. `POST /api/v1/rate/fakeslug`
req.body = {rate: 1}

2. `PATCH /api/v1/rate/fakeslug`
req.body = {rate: 2}

3. `GET /api/v1/fakeslug` 

#### What are the relevant pivotal tracker stories?
- [#167313404](https://www.pivotaltracker.com/story/show/167313404)
#### Screenshots (if appropriate)
Screen Shot 2019-08-15 at 17 22 10
Screen Shot 2019-08-15 at 17 30 44
Screen Shot 2019-08-15 at 17 30 59
Screen Shot 2019-08-15 at 17 31 07

### CODE REVIEW

**Review by Mnickii — APPROVED** [review]
LGTM

**Review by salviosage — APPROVED** [review]
LGTM

**Review by habinezadalvan — APPROVED** [review]
I went through your work and I found it impressive. Good work.

**Review by nkalyesubula — APPROVED** [review]
Nice work Patrick

**Pull request merged**
