### PR TITLE
#167313409 Users should be able to follow each other

### PR DESCRIPTION
**Pull request by nkalyesubula**
#### What does this PR do?

- Adds backend functionality for users being able to follower each other

#### Description of Task to be completed?

- Scenario 1:
Only authenticated users should be able to follow and or unfollow other users.

- Scenario 2:
I need a view to manage those I follow and be able to see those who follow me

#### How should this be manually tested?

-  Firstly, clone the repo and run **npm  run migration** and **npm run seeds**

-  Secondly, **npm run dev**.  Use this route,  **http://localhost:{port}/api/v1/users/profiles/{userId}/follow** to follow and unfollow users , use  **http://localhost:{port}/api/v1/users/profiles/following** to get all users you're following, and  **http://localhost:{port}/api/v1/users/profiles/followers** to get all your followers

#### What are the relevant pivotal tracker stories?
[#167313409 ](https://www.pivotaltracker.com/story/show/167313409)
#### Screenshots (if appropriate)
**postman**

Screen Shot 2019-08-15 at 13 53 47

Screen Shot 2019-08-15 at 13 54 13

Screen Shot 2019-08-15 at 13 58 13

Screen Shot 2019-08-15 at 13 58 31

**Swagger Documentation** 
Screen Shot 2019-08-15 at 17 35 12
Screen Shot 2019-08-15 at 17 26 23
Screen Shot 2019-08-15 at 17 26 46
Screen Shot 2019-08-15 at 17 31 40
Screen Shot 2019-08-15 at 17 32 30

### CODE REVIEW

**Review by salviosage — COMMENTED** [review]
nice work, can you give us swagger documentation screenshot in your PR

**Review by minega25 — APPROVED** [review]
LGTM

**Review by Mnickii — APPROVED** [review]
LGTM

**Review by nshutijonathan — APPROVED** [review]

**Comment by nkalyesubula** [comment]
> nice work, can you give us swagger documentation screenshot in your PR

fixed

**Review by salviosage — APPROVED** [review]
LGTM

**Pull request merged**
