### PR TITLE
 #167942825 Make API documentation more readable and interactive

### PR DESCRIPTION
**Pull request by minega25**
#### What does this PR do?
- Make API documentation more readable and interactive

#### How should this be manually tested?
Required environment variables to complete review:
- BASE_URL, PORT, API_VERSION
Run the below commands
- `git checkout -b bg-improve-api-doc-167942825`
- `git pull origin bg-improve-api-doc-167942825`
- `npm install`
- `npm run dev`
- open your web browser and open `localhost:{PORT}/api/v1/api-docs` endpoint
#### Any background context you want to provide?
- The team was facing a challenge of failing to track a typo or bug while writing swagger documentation for endpoints created. We agreed to use yaml file type to make swagger implementation easier for everyone.
Screen Shot 2019-08-19 at 17 31 38
Screen Shot 2019-08-19 at 17 31 49
Screen Shot 2019-08-19 at 17 31 59

#### What are the relevant pivotal tracker stories?
[ #167942825](https://www.pivotaltracker.com/story/show/167942825)

### CODE REVIEW

**Review by Mnickii — APPROVED** [review]
LGTM

**Review by salviosage — APPROVED** [review]
LGTM

**Review by Anguandia — APPROVED** [review]
Thanks a lot, must have been quite a sitting! Good work, like the context given to the description of the platform

**Review by habinezadalvan — APPROVED** [review]
Great work

**Review by nshutijonathan — APPROVED** [review]
LGTM

**Review by nkalyesubula — APPROVED** [review]
Nice work Patrick!

**Pull request merged**
