### PR TITLE
#167313394 Setup API documentation using swagger

### PR DESCRIPTION
**Pull request by minega25**
#### What does this PR do?
- Setup API documentation using swagger
#### Description of Task to be completed?
- create entry point of application in src/app.js
- create swagger specification implementation in src/swagger.js
- create api documentation endpoint in src/routes/api/inde.route.js
- create 404 error route handler
- create 500 error route handler
- create pull request template
#### How should this be manually tested?
Run the below commands
- `git checkout -b ch-api-documentation-167313394`
- `git pull origin ch-api-documentation-167313394`
- `npm install`
- create a `.env` file or export the following  environment variables 

[ API_VERSION=/api/v1, BASE_URL=localhost:, PORT=5000]  

- `npm run dev`
- open your web browser and open `localhost:3000/api/v1/api-docs` endpoint
#### What are the relevant pivotal tracker stories?
[#167313394](https://www.pivotaltracker.com/story/show/167313394)
#### Screenshots (if appropriate)
fullsizeoutput_f

### CODE REVIEW

**Review by nshutijonathan — COMMENTED** [review]
@patric You have some merge conflicts, please rebase from develop branch  then push again

**Review by habinezadalvan — APPROVED** [review]
The way you documented how to test your work manually is good, and easy to apply. I followed the steps and It is working well.

**Review by Mnickii — APPROVED** [review]
LGTM

**Review by nkalyesubula — APPROVED** [review]

**Comment by Anguandia** [comment]
Patrick, sorry for the belated comment, but please check the son response for the index route, make it a son object ie ({msg: "....."}) instead of (".....") Thanks

**Pull request merged**
