### PR TITLE
#167313386 Integrate TravisCI with readme badge

### PR DESCRIPTION
**Pull request by nkalyesubula**
#### What does this PR do?

-  Integrates TravisCI with readme badge

#### Description of Task to be completed?

- This is required to automatically run tests and other preliminary build steps required to ship the next iteration of the product

#### How should this be manually tested?

-  Clone the repo and retrieve the Travis CI badge code in the README file

#### What are the relevant pivotal tracker stories?

- [#167313386](https://www.pivotaltracker.com/story/show/167313386)

### CODE REVIEW

**Review by habinezadalvan — COMMENTED** [review]
Nice work @nkalyesubula, I can see that travis-ci is passing but I wonder why the README badge is still unknown. Otherwise, your codebase is good.

**Review by minega25 — CHANGES_REQUESTED** [review]
In travis.yml file. I suggest `npm ci` instead of `npm install` which means installing the whole project with a clean slate. 
Reason being It can be significantly faster than a regular npm install by skipping certain user-oriented features.

It is also more strict than a regular install, which can help catch errors or inconsistencies caused by the incrementally-installed local environments of most npm users.
The rest of the setup is fine with me.

**Comment by nkalyesubula** [comment]
> `npm ci` instead of `npm install`

Thanks Patrick, I have actually read about these two with a particular focus on configuring travis CI. All suggest use of `npm ci`  because it's significantly faster than a regular npm install.

**Comment by nshutijonathan** [comment]
> Nice work @nkalyesubula, I can see that travis-ci is passing but I wonder why the README badge is still unknown. Otherwise, your codebase is good.

I think this happens but after some hours they pass then badge becomes known and remember that we don't have tests so far

**Review by nshutijonathan — APPROVED** [review]

**Review by salviosage — COMMENTED** [review]
thanks Noah.the rest of codebase is good for me apart from Patrick's feedback, try to work on it.

**Review by minega25 — APPROVED** [review]

**Comment by nkalyesubula** [comment]
> thanks Noah.the rest of codebase is good for me apart from Patrick's feedback, try to work on it.

Fixed

**Review by Mnickii — APPROVED** [review]
LGTM

**Pull request merged**
