### PR TITLE
#167701336 failed travis ci build due to bug in app.js file

### PR DESCRIPTION
**Pull request by salviosage**
#### What does this PR do?

- fix build failure in Travis

#### Description of Task to be completed?

- all test must have to pass 

#### How should this be manually tested?

- on your local machine switch to this branch and then run `npm run test`

#### What are the relevant pivotal tracker stories?

- [#167701336](https://www.pivotaltracker.com/story/show/167701336)

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Review by Anguandia — APPROVED** [review]
Thanks Salvi, that now works, you may not have to alter the app.json file though. Please reinstate the app.json to its initial state {..., "STATE": {"required": true}, ...}. I think there was a purpose for this. Let's not loose it.
I have run the app with this setting locally and it works. 
Thanks for the hasty fixing

**Review by minega25 — CHANGES_REQUESTED** [review]
I have run the tests locally and they are passing. Great Job. However we can also fix the coveralls issue  at the same time.

**Comment by salviosage** [comment]
> Thanks Salvi, that now works, you may not have to alter the app.json file though. Please reinstate the app.json to its initial state {..., "STATE": {"required": true}, ...}. I think there was a purpose for this. Let's not loose it.
> I have run the app with this setting locally and it works.
> Thanks for the hasty fixing

Thanks Mike, I removed it because I was about to use it there and we agreed not to use it but I can put it back there for future use as well. let me try that.

**Review by minega25 — APPROVED** [review]

**Review by nkalyesubula — APPROVED** [review]
Nice fix Salvi

**Review by nshutijonathan — APPROVED** [review]
Tests are running locally from develop branch, You managed to fix this

**Pull request merged**
