### PR TITLE
#169254678 Build out get all articles for a specific user 

### PR DESCRIPTION
**Pull request by nshutijonathan**
#### What does this PR do?
-It gets all articles for a specific user
#### Description of Task to be completed?
-logged in user should be able to get all the articles he published
#### How should this be manually tested?
- Download or clone the tutorial project code from [here](https://github.com/andela/codepirates-ah-backend), in your terminal then git checkout ` ft-user-get-only-all-his-article-169254678 ` , install all required NPM packages by running NPM install from the command line in the project root folder (where the package.json is located).

- Start the API by running NPM start from the command line in the project root folder, you should see the message Server listening on port 8000. You can test the API directly using an application such as Postman or you can test it with one of the single pages in the browser.
- to test authentication and authorization, add this to the header
Key: :x-access-token,value:JWT TOKEN
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/169254678

#### Screenshots (if appropriate)
image

image

### CODE REVIEW

**Review by Anguandia — DISMISSED** [review]
LGTM doesn't break any build and serves the purpose. any defects shall be another iteration please go ahead and hasten the front-end. Good work

**Review by salviosage — COMMENTED** [review]
LGTM, tho u can shorten endpoint like `articles/mine` instead of `articles /user/article`

**Comment by nshutijonathan** [comment]
> LGTM, tho u can shorten endpoint like `articles/mine` instead of `articles /user/article`

I worked on your feedback thank you

**Review by salviosage — APPROVED** [review]

**Review by habinezadalvan — APPROVED** [review]
LGTM

**Review by minega25 — APPROVED** [review]

**Pull request merged**
