### PR TITLE
# 169124758: Article views and popular articles

### PR DESCRIPTION
**Pull request by habinezadalvan**
#### What does this PR do?

- Adds views of an article and view popular articles

#### Description of Task to be completed?
- Article views and popular articles based on views functionality. 
#### How should this be manually tested?

- Clone the repo
- run **git checkout ft-article-views-popular-articles-169124758**
- **npm install**
- **npm run dev**
- **npm run migration**
- **npm run seeds**
- Use postman:

1. login **http://localhost:3000/api/v1/users/login**, method: POST

2. create articles **http://localhost:3000/api/v1/articles**, method: POST

3. view article **http://localhost:3000/api/v1/articles/articleslug**, method: GET

4. get popular articles **http://localhost:3000/api/v1/articles?popular=popular**

#### Any background context you want to provide?
- sequelize
#### What are the relevant pivotal tracker stories?
[# 169124758](https://www.pivotaltracker.com/story/show/169124758)
#### Screenshots (if appropriate)
Screen Shot 2019-10-14 at 16 18 30

#### Questions:
none

### CODE REVIEW

**Review by Anguandia — DISMISSED** [review]
LGTM and sufficient for the moment, good work, user identity will be considered later

**Review by minega25 — DISMISSED** [review]
LGTM.

**Review by nshutijonathan — COMMENTED** [review]
Since you don't feel alright to comment out some lines of code in the feature you implemented,It's good time to sit together and help me find out the way I can finish my feature without changing your codes

**Review by salviosage — APPROVED** [review]
LGTM

**Pull request merged**
