### PR TITLE
#168243766 Add code climate badge.

### PR DESCRIPTION
**Pull request by minega25**
#### What does this PR do?
Add code climate badge to track code quality 
#### What are the relevant pivotal tracker stories?
#168243766
#### Screenshots (if appropriate)
Screen Shot 2019-09-02 at 11 34 18

### CODE REVIEW

**Review by nshutijonathan — APPROVED** [review]
LGTM, thank You for  connecting our repo to the codeclimate

**Review by nkalyesubula — APPROVED** [review]
LGTM

**Review by salviosage — APPROVED** [review]
LGTM

**Review by Mnickii — APPROVED** [review]
LGTM

**Pull request merged**
